apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QUtJQVhPVzVEV1ZLM09GWlI1TVI=
  aws_secret_access_key: VktNcVVmQ3NHdUExdEpVZ2VnV04yenM1TmQ2Zm9VOXpvd1pmeTlYVg==
